services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: schoen-klinik
    volumes:
      - mongo_db_data:/data/db
      - ./init-db:/docker-entrypoint-initdb.d
volumes:
  mongo_db_data:
    driver: local